[[FLAC]]
arch = "aarch64"
git-tree-sha1 = "f730832f6b1ba3ea547cc141ebf8be4ae058f20f"
os = "macos"

    [[FLAC.download]]
    sha256 = "f8ec8ef68961826fc5a4e9f09c8da2c4f1faecb7bb6bd064c926cf9606fe16e6"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.aarch64-apple-darwin.tar.gz"
[[FLAC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1aa5b3ae66f0e90fee7897a9f8cb99beeb9f68b2"
libc = "glibc"
os = "linux"

    [[FLAC.download]]
    sha256 = "b0be08e195248f0732a94ac8c106756f203a805468b020c0ec26df53e2d90864"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.aarch64-linux-gnu-cxx11.tar.gz"
[[FLAC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "991cf61bb2307aab76df5dc782b5934ffa290c3f"
libc = "musl"
os = "linux"

    [[FLAC.download]]
    sha256 = "ae3ea12bdb6ba55391e91cdd62b5a394cbeb5e020a0dfef1f6e8c391c52fb89f"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.aarch64-linux-musl-cxx11.tar.gz"
[[FLAC]]
arch = "aarch64"
git-tree-sha1 = "8bf2d6394453f55765fa5b76d7ab51c7c3dcc884"
os = "freebsd"

    [[FLAC.download]]
    sha256 = "629d2fccb3e8b54dff035554bb704bc6ced734f0462276f0aaae19d5a8b3d060"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.aarch64-unknown-freebsd.tar.gz"
[[FLAC]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b504040012d14f9fc3bd021685631c59058bfcdb"
libc = "glibc"
os = "linux"

    [[FLAC.download]]
    sha256 = "e2ee124b7fb8c456ddd6cd2c28288dc72246f18b3ccea7d43e41023955a46e7f"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[FLAC]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97f319cdbb9d21358d9e1ec80e1c34ad4ecba424"
libc = "musl"
os = "linux"

    [[FLAC.download]]
    sha256 = "b3e0ba3707784c6ee58157c9091a911f520f375038c3223b8274e235bdc6cbff"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[FLAC]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b1e2db7b3bfaecfb76ae83663d6ed118e5d530f"
libc = "glibc"
os = "linux"

    [[FLAC.download]]
    sha256 = "5ea2104dfff2bc135e3114498358cf65c45781f7f7a8b6b3a65ac1fa48fc97b9"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[FLAC]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ba69a21ecb61a56c8b8552c268361332608232b"
libc = "musl"
os = "linux"

    [[FLAC.download]]
    sha256 = "ac2ef7cb4ecc3f357dae89062bba4bd4d66939441d0979a3f33b49fc05213f67"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[FLAC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d44c957e33edc6e6b9d56f88f450272b48b0bb2f"
libc = "glibc"
os = "linux"

    [[FLAC.download]]
    sha256 = "50f8f3ab8c06b2590e3865b613768094a098697c593bc0747021b0837d880198"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.i686-linux-gnu-cxx11.tar.gz"
[[FLAC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3177fd6a3ccb2086d64c10662207461e9604704d"
libc = "musl"
os = "linux"

    [[FLAC.download]]
    sha256 = "d97b7d4879dde615ce239cfd8590e8c8026b5fcb7d2cdf5517c3edb131e90cd1"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.i686-linux-musl-cxx11.tar.gz"
[[FLAC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5088eb26f5ccb66f71b6c60dc6f1f60b9cbb7403"
os = "windows"

    [[FLAC.download]]
    sha256 = "66e4db92299ebea84889fd1d2916161d750fe8f3ad8bd81b5a3c37e2610c3de4"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.i686-w64-mingw32-cxx11.tar.gz"
[[FLAC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efa67b38161fc65b176344716c1e6ebdd3f6d658"
libc = "glibc"
os = "linux"

    [[FLAC.download]]
    sha256 = "768f2a78efa8f8db12dca5c4f3ec501c9df14dc8c51571d15aea66716667c65e"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[FLAC]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffdf90518cefccb99e145f45050d35b9923b809c"
libc = "glibc"
os = "linux"

    [[FLAC.download]]
    sha256 = "7c085ca57c60c71af84d270f5318cbf298436e5c3f16436577c91926ca182a25"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.riscv64-linux-gnu-cxx11.tar.gz"
[[FLAC]]
arch = "x86_64"
git-tree-sha1 = "d99592fe6901e224ee313b86f9bcc2e800d291af"
os = "macos"

    [[FLAC.download]]
    sha256 = "d4cfefa4795db5ba73b9bc2249523e2031f6f681da68ac60e19d1eea56878405"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.x86_64-apple-darwin.tar.gz"
[[FLAC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "baa52a9e9b95fdcb6b0f34fa78317df8a4d87077"
libc = "glibc"
os = "linux"

    [[FLAC.download]]
    sha256 = "6f88ba23c9d062d4b36fcabe8a76c6695eee84b66c24a838a0a6892bba17aa25"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.x86_64-linux-gnu-cxx11.tar.gz"
[[FLAC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85b09ce4fb0436cb5fb98db93948e4aed3406d35"
libc = "musl"
os = "linux"

    [[FLAC.download]]
    sha256 = "e2f4b6b496cf1f516e4f185bc27c1c6ca7685a014f56d7c7ba8a61db963f6570"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.x86_64-linux-musl-cxx11.tar.gz"
[[FLAC]]
arch = "x86_64"
git-tree-sha1 = "5f8712397ce438decd4975b0e5003664521aa813"
os = "freebsd"

    [[FLAC.download]]
    sha256 = "f6763b446f082c20a2123e686c0ce168a3ec7547a1cbf4d462561a12db1b8f8f"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.x86_64-unknown-freebsd.tar.gz"
[[FLAC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d749ddf9b1d5eed459cdf68fdad84034465e71b2"
os = "windows"

    [[FLAC.download]]
    sha256 = "f2ca236cc17f7b97cbf19bd061eb9e3d1f7ae4cba63cd8b965771e241faeaf14"
    url = "https://github.com/JuliaBinaryWrappers/FLAC_jll.jl/releases/download/FLAC-v1.4.4+0/FLAC.v1.4.4.x86_64-w64-mingw32-cxx11.tar.gz"
